# Generated by Django 2.2.3 on 2019-07-07 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='nays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='votes',
            name='ayes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='votes',
            name='vote_taken',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
